### ISSUE TITLE
Level name font responsiveness

### ISSUE THREAD

**Issue by JStrebeyko** [Quantum-Game/quantum-game-2#140]
When right beneath `1000px` screen width threshold, the level name above the board gets to its second size, way too little for, say `950px`, feels like it was created with mobile in mind.

I suggest creating another threshold around around `700px` and have the `font-size` somewhere in between the two values.

Right now the breakpoints are defined "raw", on a per component basis, which makes font management unsustainable. This might be a good time to consider a bit more holistic approach towards media queries throughout the app.

**Comment by stared** [comment]
Closed as old, and most likely not up to do date with recent code changes.
