### ISSUE TITLE
Frame flip rate increasing on additional Play buttons clicks

### ISSUE THREAD

**Issue by JStrebeyko** [Quantum-Game/quantum-game-2#141]
Apparently, every additional click on `Play` button while the simulation is already running causes the "frame flip" rate to increase and seemingly does not get down by itself. It probably has to do with nested `setInterval`s.

**Comment by stared** [comment]
@Frizi It is still an issue among many other things with controlling state.

In general, with animation, we want a smooth transition of a moving photon.

**Comment by Frizi** [comment]
I wouldn't necessarily relate smooth animations to this bug. I'm in the process of refactoring the game page, which includes the fix for the play button behaviour. Indeed there are multiple setTimeouts being started.
