### ISSUE TITLE
Explore the ways of the outside Board usage

### ISSUE THREAD

**Issue by JStrebeyko** [Quantum-Game/quantum-game-2#151]
To make the board usable as a self-contained Vue component (to accompany scientific literature, for example), there needs to be a way to export it from the game or to externalize it as a module.

**Comment by stared** [comment]
We already do that with https://github.com/Quantum-Game/bra-ket-vue/, see e.g. http://p.migdal.pl/nyc-qc-braketvue/#/

![image](https://user-images.githubusercontent.com/1001610/92921335-2a194f80-f434-11ea-9442-c080d72dca56.png)
