### ISSUE TITLE
Clean up ambiguous / redundant comments

### ISSUE THREAD

**Issue by JStrebeyko** [Quantum-Game/quantum-game-2#152]
Delete the [commented out consolelogs](https://github.com/stared/quantum-game-2/blob/master/src/engine/Grid.ts#L143) and either clarify the [FIXME](https://github.com/stared/quantum-game-2/blob/master/src/engine/Grid.ts#L2)s at place or, better, turn them into repo issues.

**Comment by stared** [comment]
Closed as old, and most likely not up to do date with recent code changes.
