### ISSUE TITLE
Linter work: fight the eslint-disable

### ISSUE THREAD

**Issue by JStrebeyko** [Quantum-Game/quantum-game-2#153]
`eslint-disable`s are used to opt out from a single rule, at-place, once.

54 are way too many, maybe it's the config that needs a tweak?
most of them also lack the details about what is the rule being circumvented, making them case-to-case issues, hard to reason about.

**Comment by sneakyweasel** [comment]
Reduced it to 26 disabled-lines and fewer blanket disable

- 4 eslint linked to d3 strange types
- v-html seems needed
- some any eslint from userStore and associated files
- some any for core Vue files 
- some require
