### ISSUE TITLE
For Friday presentation

### ISSUE THREAD

**Issue by KlemKlem** [Quantum-Game/quantum-game-2#157]
- [ ] Absorption/"fate" - should pulse only once, but each time an absorption happens. Should happen when measurement happens, which is not always at the end of the level
- [ ] Play button - remove from encyclopedia mini boards, 
- [x] Play button - remove hint circle around the button
- [ ] Bomb - it shouldn't always explode, should depend on the measurement
- [x] Goals - fix - goals donut doesn't update
- [ ] Transition matrix - add legend + style
- [x] Graph - fast redesign for the purpose of Friday presentation
- [x] Encyclopedia landing page - for chrome
- [ ] "Dark" mode - for when the photon is moving on the board

![QG_photon_running01](https://user-images.githubusercontent.com/33489641/70721352-afc96c80-1cf5-11ea-9f16-c9c06e22e82f.png)
![QG_photon_running02](https://user-images.githubusercontent.com/33489641/70721353-b0620300-1cf5-11ea-8273-4ec08b25e288.png)
![QG_photon_running03](https://user-images.githubusercontent.com/33489641/70721355-b0620300-1cf5-11ea-9db9-3be6ff6326a9.png)

**Comment by stared** [comment]
A nice moment to look at the past. Now, let's move on. :)
