### ISSUE TITLE
Polarizer and QWP orientation and computation

### ISSUE THREAD

**Issue by sneakyweasel** [Quantum-Game/quantum-game-2#169]
@KlemKlem 
In order to use Polarizer and Quarter Wave Plate cells we need to be able to input their polarization and rotation is already mapped with mouse click.
We could imagine using a small parameters panel made available when the element has more inputs.
I also checked the reason why the SVG was not displaying the lines once the element is moved and it's linked with: 
`<clipPath id="clip">
 <circle cx="32" cy="32" r="28" />
</clipPath>`

@stared 
We need to transmit polarization and rotation to quantum-tensors ops to generate the correct transition matrix, how should I proceed?

**Comment by stared** [comment]
Changed it a lot. Now there is one oversimplification with physics, but overall it makes more sense with the current interface (starting from May 2020):
https://github.com/Quantum-Game/quantum-game-2/blob/master/CHANGELOG.md#2211---2020-05-08
