### ISSUE TITLE
Firebase user login

### ISSUE THREAD

**Issue by stared** [Quantum-Game/quantum-game-2#182]
Firebase user login does not seem to work:

![image](https://user-images.githubusercontent.com/1001610/77943163-12eb0900-72bd-11ea-80cc-d694b3b60381.png)

Before release, it would be great if we could:

* [x] make it work (at least one way to login)
* [x] display somewhere login status (for all screens, some small text in one of the corners, e.g. `Click to log in` (and directed to the login page) vs `Playing as [name/email]` (link to the published levels)
* [x] this listing of saved levels, with a way to make it public 

All of such things seemed to work to some extend (at least the login part).

**Comment by JStrebeyko** [comment]
We figured out point number one, here is a [PR](https://github.com/Quantum-Game/quantum-game-2/pull/186) for point number two.
I will proceed to point number three on the same branch
