### ISSUE TITLE
Consider Asynchronocity in GamePage template

### ISSUE THREAD

**Issue by JStrebeyko** [Quantum-Game/quantum-game-2#197]
As of now, some logic throws on initial load if there is no logic data present, probably because elements are awaiting an `activeFrame`. A possible solution could be for example setting some alternative (default) `activeFrame` on load or perhaps making the prop optional futher down the component tree.

DOD: the `GameComponent` does not throw on levels being loaded from db.

**Comment by stared** [comment]
Old, with current changes, might be not up to date. Closing.
