### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ask4physics** [Quantum-Game/quantum-game-2#222]
Have installed yarn v1.22.4
When running the game with:
`yarn serve` in Node.js command prompt,
the following error is observed:
![error-screen](https://user-images.githubusercontent.com/64779944/91637374-8777ce80-ea3a-11ea-9965-1bc63a1defb1.PNG)

**Comment by ask4physics** [comment]
Using yarn v1.22.5 on another machine yielded the following error:

> Error loading vue.config.js:

![code-10092020](https://user-images.githubusercontent.com/64779944/92705769-8d4ca880-f386-11ea-83ac-c3936125e8e3.PNG)

**Comment by stared** [comment]
Right now we are in the process of changes - as we started working on it full time starting from this month. The newest version on master (not yet deployed on <https://quantumgame.io>) uses Vue 3 (#227).

If you want to run it locally:

* clone it
* `git pull` (if there is a newer version)
* `yarn` (to update dependencies)
* `yarn serve`

Note that there are are a few breaking changes with the last edits. Right now the last stable version (Vue 2) is https://github.com/Quantum-Game/quantum-game-2/releases/tag/v2.2.13.

Let me know if it helps!

**Comment by Frizi** [comment]
This is definitely a fail of `last-commit-log` package, which we use in vue.config.js. Looks like the repository was downloaded as zip or something, so there is no git metadata. We can either mention that in README, or handle the exception and provide some made-up build version info as a placeholder.
