### ISSUE TITLE
Tone.js: "AudioContext was not allowed to start" warning

### ISSUE THREAD

**Issue by stared** [Quantum-Game/quantum-game-2#237]
When opening the main page, there is a warning (or actually: MANY warnings).

<img width="407" alt="Screenshot 2020-10-03 at 11 17 16" src="https://user-images.githubusercontent.com/1001610/94987927-10b67f80-056a-11eb-916a-1bc5b7f8c8fa.png">

AFAIR Tone.js can be initialized only after user input.

**Comment by Frizi** [comment]
The "audio not starting" part of the issue can be fixed, but the warning will still be there. It will always appear at least a few times, as this is simply what chrome does on audio context creation. Tone creates it immediately on import and deferring the import isn't worth it. Also the only way to check if the browser requires the event is to create the context and see if it's already running. So the warning is inevitable.
