### ISSUE TITLE
Photon's opacity

### ISSUE THREAD

**Issue by KlemKlem** [Quantum-Game/quantum-game-2#99]
After measurement in one place, the opacity in the second place is degrading instead of increasing. 
![Screenshot 2019-11-12 at 3 49 15 PM](https://user-images.githubusercontent.com/33489641/68657413-a02bfc00-056e-11ea-9284-4f0867ac486f.png)
![Screenshot 2019-11-12 at 3 49 09 PM](https://user-images.githubusercontent.com/33489641/68657419-a3bf8300-056e-11ea-988c-406efde2bfe0.png)

**Comment by sneakyweasel** [comment]
Seems to be working.
<img width="219" alt="fix2" src="https://user-images.githubusercontent.com/921073/74058532-8885d780-49e6-11ea-8532-b01df488ac35.png">
<img width="218" alt="fix1" src="https://user-images.githubusercontent.com/921073/74058533-891e6e00-49e6-11ea-8d5c-5e7915374e6a.png">

**Comment by sneakyweasel** [comment]
The opacity isn't changing with out of bounds photon anymore.
